### ISSUE TITLE
Compile error in the derive.idr file

### ISSUE THREAD

**Issue by antonkri97** [andorp/order-taking#4]
In the Idris 2, version 0.4.0

Output of the `make typecheck` command is

```
16/35: Building Rango.DataTransfer.JSON.Derive (src/Rango/DataTransfer/JSON/Derive.idr)
Error: Couldn't parse declaration.

Rango.DataTransfer.JSON.Derive:90:1--90:2
 86 | ||| @ opts The automatic derivation options.
 87 | ||| @ name The name of the type to derive for. Can be without namespace if unambigous.
 88 | public export covering
 89 | deriveToJSON : (opts : JSONDeriveOpts) -> (name : Name) -> Elab ()
 90 | deriveToJSON opts n = do
```

https://github.com/idris-community/idris2-lsp/blob/idris2-0.4.0/src/Language/LSP/Message/Derive.idr

Checkout special 0.4.0 git branch, there are some breaking changes. 

I'd like to do it by myself, but literally I just started to learn all this stuff, so it's quite complicated for me :(

**Comment by andorp** [comment]
This breaking change was introduced after the 0.4.0 Idris2 release.

Sorry for the inconvenience, but you should use the dedicated version of the Idris2 compiler which is tagged in the VERSIONS file. In case if you don't want to update your Idris2 compiler, your other option is to use a compatible commit;
https://github.com/andorp/order-taking/blob/279a317bb65fcd9339552b7a9e1543dd3ae13737

I hope this helps.

**Comment by antonkri97** [comment]
Sorry, I did not check VERSIONS file.

But where I can find this particular version `0.4.0-1b6cc3ba1`?

It all simple In the releases [page](https://github.com/idris-lang/Idris2/releases), just 0.2.0 -> 0.3.0 -> 0.4.0

**Comment by andorp** [comment]
I use the `main` branch from the Idris repository. It is very easy to compile the Idris compiler from scratch, it takes less than 10 mins. Read the INSTALL.md . I usually update my setup every Sunday afternoon.

As an alternative I created the `0.4.0` tag. The architecture haven't changed much since then.
https://github.com/andorp/order-taking/releases/tag/0.4.0

I hope this helps.
